### ISSUE TITLE
Doesn't work in Joomla

### ISSUE THREAD

**Issue by vingle** [aydun/uk.squiffle.kam#12]
Seems to be two issues:
 - relatively trivial padding/positioning quirk which has the search menu item running over the search box (NB, screengrab is on the Joomla.css from 5.8, issue is the same in 5.7).

![image](https://user-images.githubusercontent.com/1175967/48196281-0ec9ee80-e34a-11e8-8f9f-5d030f7e6ea0.png)

 - a Javascript error "Empty string passed to getElementById()." which prevents the drop down from working either using click or keyboard control.

At responsive view, there is also some positioning problems and while the initial dropdown from the burger triggers the dropdown (tho fires the same error into the console), the second/etc levels don't.

![image](https://user-images.githubusercontent.com/1175967/48196454-8861dc80-e34a-11e8-97c1-b8fb8f754cc1.png)

**Comment by aydun** [comment]
Item 1 fixed 
Item 2 TBD

**Comment by colemanw** [comment]
Fixed via https://github.com/aydun/uk.squiffle.kam/pull/21
