### ISSUE TITLE
bower/npm installation instructions??

### ISSUE THREAD

**Issue by JoeMurray** [aydun/uk.squiffle.kam#15]
I see that this uses the https://github.com/aydun/uk.squiffle.kam/tree/master/packages/smartmenus-1.1.0 library that is installable by bower and npm. 

Do we want to support a composer/bower based install for D8? Or use the packages dir approach of the last 10+ years in Civi which tends to have libraries get out of date but with the advantage of having control when they are updated?

**Comment by aydun** [comment]
Since @colemanw is planning to merge this to core, I guess this will follow the pattern for other libraries used by core.
