### ISSUE TITLE
Additional markup required to access menu items in responsive mode

### ISSUE THREAD

**Issue by christianwach** [aydun/uk.squiffle.kam#17]
I've been trying to get this extension working of WordPress (in preparation for its inclusion in core) and have made some progress but it gets complicated by the requirement for `#civicrm-menu-nav` to have `position: fixed` on WordPress in order for the menu to be rendered above the WordPress admin menu. 

This is fine on desktop-sized screens, but I see that this menu implementation (sensibly) rearranges its display for smaller screens. However, as it stands, I cannot find a combination of CSS declarations that allow access to items that are below the bottom of the viewport on WordPress. For example, any of the lower items in the "System Settings" menu:

<img width="376" alt="screen shot 2018-11-16 at 12 42 21" src="https://user-images.githubusercontent.com/726936/48622020-5fba9200-e99d-11e8-9476-d58b4125af81.png">

I notice that the same problem exists on Drupal 7 as well.

I'd like to implement `overflow-y: scroll` on a container element for `ul#civicrm-menu` (which is tricky to do when `#civicrm-menu-nav` has `position: fixed` but can be done) but this will require some extra markup e.g. a `<div>` (or maybe two) wrapping `ul#civicrm-menu`.

Would additions to the markup mess up the styles for Drupal & Joomla? Have you looked at small-screen behaviour and I've missed a trick?

**Comment by colemanw** [comment]
I agree, please go ahead and send in a PR with the additional markup and we'll test it in the other CMSs to make sure it is cross-compatible.

**Comment by christianwach** [comment]
I've found a way to make `overflow-y: scroll` work with the existing markup.

**Comment by colemanw** [comment]
@christianwach care to share? Something we should put in the css for this extension?

**Comment by christianwach** [comment]
> care to share?

All the fixes are in [CAU](https://wordpress.org/plugins/civicrm-admin-utilities/). Enable the plugin and check the box labelled "Check this to apply to the CiviCRM menu" and you'll see how CAU amends KAM. All the declarations live in [this file](https://github.com/christianwach/civicrm-admin-utilities/blob/master/assets/css/civicrm-admin-utilities-kam.css).
