### ISSUE TITLE
Latest version completely breaks menu in Joomla

### ISSUE THREAD

**Issue by vingle** [aydun/uk.squiffle.kam#19]
This version is fully broken on Joomla.

Before (Civi 5.8 / Joomla 3.9):

![image](https://user-images.githubusercontent.com/1175967/48775636-8b9f8580-ecc5-11e8-8f60-5add94ce0e09.png)

After

![image](https://user-images.githubusercontent.com/1175967/48775714-c9041300-ecc5-11e8-8ae8-35747be1b2b5.png)

I tried disabling the new Joomla CSS (https://github.com/civicrm/civicrm-core/pull/12956) but the Civi menu is still absent. I also tried the 'master', 'menubar' and 'css' branches - all show no menu. FWIW I'm not getting any JS errors.

**Comment by vingle** [comment]
I don't know if this is any help, but in my limited attempts to debug this — the point of failure in the output HTML relates to the line loading the menu in /civicrm/templates/CRM/common/joomla.tpl:
`{crmNavigationMenu is_default=1} `. If I disable the extension and comment out that line I get the same behavior of missing menu.

The function I'm guessing is function smarty_function_crmNavigationMenu in com_civicrm/civicrm/CRM/Core/Smarty/plugins/function.crmNavigationMenu.php . I'm not seeing any PHP errors in the log. I'm pretty out of my depth here — about the furthest I got in searching some of the function names, was KAM's ajax.php references `buildNavigationTree` in core/BAO and smarty_function_crmNavigationMenu references `buildNavigation` in core/BAO. 

I'm guessing at the heart of this is the fact that Joomla's Civi menu sits under the CMS menu — while in Drupal and Wordpress it sits on top of the CMS menu and you have to toggle hide it to do something in the CMS (which seems suboptimal imho but obvs is standard behaviour). Another (ideal?) option would be to inject the Civi menu into Joomla's Subheader - hidden from Civi 5.8 onwards but designed for component specific menus, and which is fixed at the top on scroll (the grey bar below)

Another option would be to inject the Civi menu into Joomla's Subheader - hidden from Civi 5.8 onwards but designed for component specific menus, and which is fixed at the top on scroll (the grey bar below)

![image](https://user-images.githubusercontent.com/1175967/48843155-2bc0e180-ed8e-11e8-91c5-1b7c59f0bbb8.png)

**Comment by colemanw** [comment]
Fixed via https://github.com/aydun/uk.squiffle.kam/pull/21
