### ISSUE TITLE
Kam breaks quicksearch

### ISSUE THREAD

**Issue by eileenmcnaughton** [aydun/uk.squiffle.kam#45]
As of today I installed KAM on https://dmaster.demo.civicrm.org and it breaks quick search

The issue is the handling of the search type (email, contact id etc) & appears to be js related

I find the easiest way to replicate is to choose to search by contact id & use id 202 

![kam](https://user-images.githubusercontent.com/336308/52593202-3d0d1c00-2ead-11e9-8551-528c7e248ed3.gif)

**Comment by colemanw** [comment]
Err, I can't reproduce this:
![screenshot from 2019-02-11 16-15-08](https://user-images.githubusercontent.com/2874912/52594009-6a5bba80-2e18-11e9-9f20-8b338cc9e393.png)

**Comment by eileenmcnaughton** [comment]
Hmm - there seems to be some stickiness aspect to it - try changing to various others & retrying

**Comment by aydun** [comment]
It depends whether you click on the words or the circle indicators:

- Clicking on the menu words (Contact ID, External ID etc) works as expected.
- But if you click on the circles as in Eileen's screengrab the label in the quick search box changes, but the circle indicator does not change nor does the type of search actually performed.

**Comment by colemanw** [comment]
Ahh. Thanks for the clarification @aydun 

Debugging this now -- looks to be caused by a series of unfortunate event handlers. Looking for a solution.

**Comment by colemanw** [comment]
Ok this ought to do it. @aydun can you check ^

**Comment by aydun** [comment]
@colemanw Yup - that fixes it for me.
