### ISSUE TITLE
Hover does not work while viewing a contact

### ISSUE THREAD

**Issue by magnolia61** [aydun/uk.squiffle.kam#48]
Great extension, no problems whatsoever, except one strange issue.
When I am viewing a contact, hovering the kam menu does not work anymore.
Console says: Error: Syntax error, unrecognized expression: unsupported pseudo: hover
in civicrm_extensions/uk.squiffle.kam/js/crm.menubar.js?r=FW11f:76

**Comment by magnolia61** [comment]
There seems to be a conflict with another extension: https://github.com/CiviCooP/org.civicoop.postcodenl
Not sure which of the two would be the easiest to change a line to a more specific label.

**Comment by colemanw** [comment]
I believe the fix to the problem lies in this patch to the postcodenl extension: https://github.com/CiviCooP/org.civicoop.postcodenl/pull/18
