### ISSUE TITLE
draggable civi icon

### ISSUE THREAD

**Issue by eileenmcnaughton** [aydun/uk.squiffle.kam#49]
It turns out the 'civi' icon is within the draggable area.... see gif ( this is something our user found herself doing by accident)

![kamdrag](https://user-images.githubusercontent.com/336308/53126261-94ee0600-35c4-11e9-8270-230afff65264.gif)

**Comment by colemanw** [comment]
It looks to me like you can do that with anything on the page. I just tried selecting some text on the page and successfully dragged it into the quicksearch box.
I think that's just the way browsers work - you can drag any text into a textfield. However I agree that you usually don't want to drag menu items anywhere.
How about this: https://github.com/aydun/uk.squiffle.kam/pull/53
