### ISSUE TITLE
Kam breaks search results

### ISSUE THREAD

**Issue by eileenmcnaughton** [aydun/uk.squiffle.kam#52]
OK I have a second serious issue with KAM - unfortunately this concludes our live testing for now - we've turned it off again.

The issue is that kam interacts with an underlying search result in some way. 

This is what happens without KAM - I do a search on 'contact id' & wind up on advanced search. I then do another search on 'name = Bob' & get a list of Bobs

![searchstickybefore](https://user-images.githubusercontent.com/336308/53135728-3c793180-35e1-11e9-9992-9a110208eded.gif)

After I enable KAM I get no results for the second search and you can see the contact_id criteria has not been cleared out.

![searchstickyaftet](https://user-images.githubusercontent.com/336308/53135767-5fa3e100-35e1-11e9-92b8-f5c7e5eecadf.gif)

We found this hard to replicate since you need to use the screens in a certain order, but I think the key is to be searching from an existing advanced search page.

We are running against the 5.11 rc

**Comment by colemanw** [comment]
@eileenmcnaughton can you try #54 

What was your 1st serious issue?

**Comment by eileenmcnaughton** [comment]
@colemanw the first one was the one you fixed already - both were 'serious' in that our users couldn't search - although the first turned out to be that they clicked on the radio buttons & you clicked on the names - but from their POV it was 'broken'

**Comment by eileenmcnaughton** [comment]
@colemanw the linked patch worked for me just now!
